language: python
sudo: false
cache:
  pip: true
  directories:
    - $TRAVIS_BUILD_DIR/buildout-cache
python:
  - 2.7
addons:
  apt:
    packages:
    - libpcre3
    - libpcre3-dev
    - libssl-dev
    - libexpat1-dev
    - gnuplot
    - libgdk-pixbuf2.0-0
    # needed libs for chromedriver
    # - libnss3-dev
    # - libgconf-2-4
before_script:
  ### Install the latest chromedriver manually from https://sites.google.com/a/chromium.org/chromedriver/downloads
  # NB: must be setuid root to move this executable
  #     => commented out, since the chrome browser exits unexpeted and the robot tests are not passing anyhow
  # - wget http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip
  # - unzip chromedriver_linux64.zip
  # - sudo mv chromedriver /usr/bin/
  ###
  - export DISPLAY=99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - mkdir -p $TRAVIS_BUILD_DIR/buildout-cache/{eggs,downloads}
  - echo "[buildout]" > $TRAVIS_BUILD_DIR/default.cfg
  - echo "download-cache = $TRAVIS_BUILD_DIR/buildout-cache/downloads" >> $TRAVIS_BUILD_DIR/default.cfg
  - echo "eggs-directory = $TRAVIS_BUILD_DIR/buildout-cache/eggs" >> $TRAVIS_BUILD_DIR/default.cfg
  - virtualenv .
  - bin/pip install --upgrade pip setuptools zc.buildout
install:
  - bin/buildout -n -t 3 -c travis.cfg
script:
  - bin/test -m bika.lims --layer=bika.lims.testing.BikaTestingLayer:Functional
  - bin/test test_textual_doctests
